[build]
  publish = "__sapper__/export"
  command = "yarn export"
  functions = "src/lambda/"

[dev]
  functions = "src/lambda/"
  command = "yarn dev" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  publish = "__sapper__/dev"